version: '3.0'

services:
  main:
    container_name: main
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    run:
      command: npm run start
      args: --port 8080
      containerPort: 8080